# Generated by Django 4.1 on 2023-02-19 12:38

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Atributs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True, verbose_name='Name')),
                ('deckription', models.JSONField(blank=True, null=True, verbose_name='Deckription')),
                ('icon', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='ctg_icons')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='ctg_image')),
                ('cotalog', models.FileField(blank=True, null=True, upload_to='cotalog_fiels', verbose_name='Cotalog for download')),
                ('atributs', models.ManyToManyField(blank=True, null=True, to='admins.atributs')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Slug')),
                ('hex', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Slug')),
                ('type', models.JSONField(blank=True, null=True, verbose_name='Type')),
                ('manufacturer', models.JSONField(blank=True, null=True, verbose_name='Manuf')),
                ('description', models.JSONField(blank=True, null=True, verbose_name='Descr')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='admins.category')),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.metatags')),
            ],
        ),
        migrations.AlterField(
            model_name='shortapplication',
            name='nbm',
            field=models.CharField(default='9898988', max_length=255, verbose_name='Nbm'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='variant_images')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
                ('top', models.BooleanField(default=False, verbose_name='Top')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.colors')),
                ('options', models.ManyToManyField(blank=True, null=True, to='admins.atributoptions')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='admins.products')),
            ],
        ),
        migrations.AddField(
            model_name='atributoptions',
            name='atribut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='admins.atributs'),
        ),
        migrations.AddField(
            model_name='shortapplication',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.productvariants'),
        ),
    ]
