# Generated by Django 4.1 on 2023-02-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_atributoptions_atributs_category_colors_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='productvariants',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariants',
            name='options',
        ),
        migrations.RemoveField(
            model_name='productvariants',
            name='product',
        ),
        migrations.RemoveField(
            model_name='category',
            name='atributs',
        ),
        migrations.RemoveField(
            model_name='shortapplication',
            name='product',
        ),
        migrations.DeleteModel(
            name='AtributOptions',
        ),
        migrations.DeleteModel(
            name='Atributs',
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProductVariants',
        ),
    ]
