# Generated by Django 4.1 on 2023-02-19 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_remove_products_category_remove_products_meta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminInputs',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='eventimages',
            name='event',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='ShortApplication',
        ),
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.FloatField(default=23, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventImages',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
