# Generated by Django 4.1 on 2023-02-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_delete_admininputs_delete_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegalleryfiles',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='videogalleryvideos',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='ArticleImages',
        ),
        migrations.DeleteModel(
            name='ImageGalery',
        ),
        migrations.DeleteModel(
            name='ImageGalleryFiles',
        ),
        migrations.DeleteModel(
            name='VideoGalery',
        ),
        migrations.DeleteModel(
            name='VideoGalleryVideos',
        ),
    ]
