# Generated by Django 4.1 on 2023-02-19 16:42

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True, verbose_name='Name')),
                ('deckription', models.JSONField(blank=True, null=True, verbose_name='Deckription')),
                ('icon', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='ctg_icons')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='ctg_image')),
                ('cotalog', models.FileField(blank=True, null=True, upload_to='cotalog_fiels', verbose_name='Cotalog for download')),
            ],
        ),
        migrations.CreateModel(
            name='ShortApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('nbm', models.CharField(max_length=255, verbose_name='Nbm')),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('status', models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Рассмотрено', 'Рассмотрено'), ('Отклонено', 'Отклонено')], default='На рассмотрении', max_length=255, verbose_name='Status')),
                ('type', models.CharField(choices=[(1, 'Веб и корпоративный'), (2, 'Bеб приложение'), (3, 'Мобильный'), (4, 'Брендинг логотипа')], max_length=255, verbose_name='Type')),
                ('budget', models.CharField(choices=[(1, '300$'), (2, '500$ - 700$'), (3, '700$ - 1000$'), (4, 'Согласны')], max_length=255, verbose_name='Budget')),
                ('project_idea', models.TextField(blank=True, null=True, verbose_name='Idea')),
                ('know_about_you', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True, verbose_name='Name')),
                ('description', models.JSONField(blank=True, null=True, verbose_name='Desc')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='project_logos', verbose_name='Logo')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='project_images')),
                ('categpries', models.ManyToManyField(blank=True, null=True, to='main.category')),
            ],
        ),
    ]
